%YAML:1.0
# generic_camera.yaml  – pinhole, radial‑tangential distortion (all zero)

# --------------------------------------------------------------
# BASIC CAMERA INFO
# --------------------------------------------------------------

Camera.type: "PinHole"
Camera.name: generic_cam
Camera.type: PinHole                # pinhole = fx,fy,cx,cy
Camera.fps: 30.0                     # change if your video runs at a different FPS
Camera.width: 480                    # <-- put your real image width here
Camera.height: 480                   # <--           ...height here

# --------------------------------------------------------------
# INTRINSICS
# --------------------------------------------------------------
Camera.fx: 207.87
Camera.fy: 207.87
Camera.cx: 240.0
Camera.cy: 240.0

# --------------------------------------------------------------
# DISTORTION (set to zero = ideal lens)
# --------------------------------------------------------------
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.RGB: 1
  # if you have higher‑order radial terms, add k3‑k6 here

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
